<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapySR.Common\CapySR.Common.csproj" />
    <ProjectReference Include="..\CapySR.Protocol\CapySR.Protocol.csproj" />
  </ItemGroup>

</Project>
